schema_version: 1

context:
  name: fastcluster
  version: 1.3.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: d5233aeba5c3faa949c7fa6a39345a09f716ccebbd748541e5735c866696df02

build:
  number: 0
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - if: build_platform != target_platform
      then:
      - python
      - cross-python_${{ target_platform }}
      - numpy
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - ${{ compiler('cxx') }}
  host:
    - python
    - pip
    - setuptools
    - wheel
    - numpy
  run:
    - python

tests:
  - python:
      imports:
        - fastcluster
      pip_check: true

about:
  license: BSD-2-Clause
  license_file: COPYING.txt
  summary: Fast hierarchical clustering routines for R and Python.
  description: |
    This library provides Python functions for hierarchical clustering. It generates hierarchical
    clusters from distance matrices or from vector data.

    Part of this module is intended to replace the functions
    linkage, single, complete, average, weighted, centroid, median, ward
    in the module scipy.cluster.hierarchy with the same functionality but much faster algorithms.
    Moreover, the function linkage_vector provides memory-efficient clustering for vector data.

    The interface is very similar to MATLAB’s Statistics Toolbox API to make code easier to
    port from MATLAB to Python/NumPy. The core implementation of this library is in C++ for efficiency.
  homepage: http://danifold.net/fastcluster.html
  repository: https://github.com/dmuellner/fastcluster
  documentation: https://github.com/dmuellner/fastcluster/raw/master/docs/fastcluster.pdf

extra:
  recipe-maintainers:
    - mpharrigan
    - synapticarbors
